# Generated by Django 4.1.3 on 2022-11-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='userId',
            new_name='user',
        ),
    ]
