# Generated by Django 4.1.3 on 2022-11-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderId',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='productId',
            new_name='product',
        ),
    ]
