# Generated by Django 4.1.3 on 2022-11-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='test',
            field=models.CharField(default='Test', max_length=12),
        ),
    ]
