# Generated by Django 4.1.3 on 2022-11-11 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 16, 12, 56, 354905), verbose_name='date published'),
        ),
    ]
