# Generated by Django 4.1.3 on 2022-11-11 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 11, 16, 14, 7, 673467), verbose_name='date published'),
        ),
    ]
